
coverage_service: html
xcodeproj: Authenticator.xcodeproj
workspace: Authenticator.xcworkspace
scheme: Authenticator-Example
binary_file: DerivedData/Authenticator/Build/Products/Debug-iphonesimulator/TestHost-iOS.app/PlugIns/Authenticator_Tests.xctest/Authenticator_Tests
output_directory: coverage_reports
ignore:
    - Authenticator/View Controllers/*
    - Authenticator/Views/*
    - Tests/*
    - Pods/*
    - Authenticator/Supporting Files/AppDelegate.swift
    - Authenticator/Utils/Extensions/ApplicationExtensions.swift
    - Authenticator/Utils/Extensions/BordersExtensions.swift
    - Authenticator/Utils/Extensions/WindowExtensions.swift
    - Authenticator/Utils/Extensions/ViewControllerExtensions.swift
    - Authenticator/Utils/Helpers/HapticFeedbackHelper.swift
    - Authenticator/Utils/Helpers/NotificationsManager.swift
